<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tla</string>
	</array>
	<key>name</key>
	<string>TLA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\\*.*$</string>
			<key>name</key>
			<string>comment.line.slash-star</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\h[0-9a-fA-F]+|\\o[0-9]+|\\b[01]+|\d+\.\d+|\d+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved-words</string>
			<key>match</key>
			<string>[a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved-words</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>reserved-words</key>
		<dict>
			<key>match</key>
			<string>\b(ASSUME|ASSUMPTION|AXIOM|CASE|CHOOSE|CONSTANT|CONSTANTS|DOMAIN|ELSE|ENABLED|EXCEPT|EXTENDS|IF|IN|INSTANCE|LET|LOCAL|MODULE|OTHER|SF_|SUBSET|THEN|THEOREM|UNCHANGED|UNION|VARIABLE|VARIABLES|WF_|WITH)\b</string>
			<key>name</key>
			<string>keyword.control.tla</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>A29E70ED-6D0F-4997-84E9-528B8EC412A1</string>
</dict>
</plist>
